spring.datasource.url=jdbc:postgresql://localhost:5432/koa_sleep?currentSchema=public
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=dev
server.servlet.context-path=/api/v1
jwt.secret=IUdeoDgPSOxf6tlRWK4itlpmcLgSpQpQIZ6r2LtSm7c
jwt.expiration=3600000
app.frontend-url=http://localhost:3000