spring.application.name=koa-sleep-core
spring.datasource.url=postgresql://admin:admin@localhost:5432/koa_sleep?schema=public
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate